### ISSUE TITLE
Add vulkansdk/bin to path

### ISSUE THREAD

**Issue by ThomasAunvik** [jakoch/install-vulkan-sdk-action#453]
I noticed that here it is commented out:

https://github.com/jakoch/install-vulkan-sdk-action/blob/8578878e93982f505382ec58ca42a85a0b740639/src/main.ts#L142-L152

But the path that is added is not the bin folder, and only the install folder, which doesn't include all the executables that vulkansdk gives.

And I would not be able to execute `glslc`.

And the docs points to the bin folder, and not the install folder:
![image](https://github.com/user-attachments/assets/e28b1e9b-47c3-4d27-9e05-4823c21e5469)

https://vulkan.lunarg.com/doc/sdk/1.3.261.1/linux/getting_started.html#set-up-the-runtime-environment

In which case, I would have to add this as an alternative to my github action:
```yml
      - name: Setup Linux Env
        if: contains(runner.os, 'ubuntu')
        run: source $VULKAN_SDK/setup-env.sh

      - name: Setup Windows Env
        if: contains(runner.os, 'windows')
        run: $env:PATH += ";$env:VULKAN_SDK\Bin" # have not really found out how to fix it on windows, seems not working
```
